name: BetterCommunication
version: '${version}'
main: io.github.severnarch.bettercommunication.BetterCommunication
api-version: '1.20'
load: STARTUP
description: A plugin made towards improvement of the Minecraft chat and its communication features.
folia-supported: true
commands:
  bettercommunication:
    description: The main command for BetterCommunication.
    permission: bettercommunication.bettercommunication
permissions:
  bettercommunication.bettercommunication:
    description: Access to /bettercommunication

  bettercommunication.mention:
    description: Access to mentioning players (@).
    default: op
  bettercommunication.mention.ping:
    description: Requires bettercommunication.mention; plays a ping sound to mentioned players
    default: op
